const os = require('node:os')
console.log('sistema operativo', os.platform())
console.log('version del sistema operativo', os.release())
console.log('arquitectura del sistema operativo', os.arch())
console.log('memoria total', os.totalmem() / 1024 / 1024)
console.log('memoria libre', os.freemem() / 1024 / 1024)
console.log('numero de procesadores', os.cpus())
console.log('uptime', os.uptime() / 60 / 60 / 24)
